spring.data.mongodb.database=mongo_db
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017

# App Properties
signup.app.jwtCookieName= signupCookie
signup.app.jwtSecret= ======================signupCookie=Arijit===========================
signup.app.jwtExpirationMs= 86400000